name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Print Environment Variables
        run: |
          echo "VERCEL_TOKEN: $VERCEL_TOKEN"
          env  # Print all environment variables
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-project-name: pokeapi
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
