name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Print Environment Variables and Secrets
        run: |
          echo "Printing Environment Variables:"
          env  # Print all environment variables
          echo "Printing Secrets:"
          printenv | grep -E '^(.*?)=(.*)$'
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.1.1
        env:
          vercel-project-name: pokeapi
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

